POST /test/img.jpg HTTP/1.1
Host: localhost:7995
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:91.0) Gecko/20100101 Firefox/91.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: multipart/form-data; boundary=---------------------------34225751403987863211877742919
Content-Length: 1008
Origin: http://localhost:7995
Connection: keep-alive
Referer: http://localhost:7995/index.html
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1

-----------------------------34225751403987863211877742919
Content-Disposition: form-data; name="file"; filename="Makefile"
Content-Type: application/octet-stream

NAME = webserv

PATH_SRC = ./srcs/
SRCS = main.cpp Config.cpp Location.cpp Server.cpp Socket.cpp regexp.cpp  Request.cpp count_words.cpp response_error_header.cpp error_tables.cpp \
		string_manip.cpp requ